version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - 127.0.0.1:5999:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fixme
      POSTGRES_PASSWORD: fixme
      POSTGRES_DB: airflow
      TZ: "Europe/Amsterdam"
    restart: always
  scheduler:
    depends_on:
      - postgres
    image: guangie88/airflow-pipeline:1.10_spark-2.4.4_hadoop-3.1.0_python-3.6_sqlalchemy-1.1
    volumes:
      - ./dags:/airflow/dags:ro
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     AIRFLOW_VERSION: "1.10"
    #     SPARK_VERSION: "2.4.4"
    #     HADOOP_VERSION: "3.1.0"
    #     PYTHON_VERSION: "3.6"
    #     SQLALCHEMY_VERSION: "1.1"
    #     SPARK_PY4J: "python/lib/py4j-0.10.7-src.zip"
    #     AIRFLOW_SUBPACKAGES: ""
    network_mode: "host"
    volumes:
      - ./dags:/airflow/dags:ro
      - ./airflow.cfg:/airflow/airflow.cfg:ro
      - airflow_logs:/airflow/logs
    environment:
      AIRFLOW__CORE__FERNET_KEY: 8NE6O6RcTJpxcCkuKxOHOExzIJkXkeJKbRie03a69dI=
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://fixme:fixme@localhost:5999/airflow
      TZ: "Europe/Amsterdam"  # Doesn't affect DAG trigger / cron
    restart: always
  webserver:
    image: guangie88/airflow-pipeline:1.10_spark-2.4.4_hadoop-3.1.0_python-3.6_sqlalchemy-1.1
    volumes:
      - ./dags:/airflow/dags:ro
      - ./airflow.cfg:/airflow/airflow.cfg:ro
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     AIRFLOW_VERSION: "1.10"
    #     SPARK_VERSION: "2.4.4"
    #     HADOOP_VERSION: "3.1.0"
    #     PYTHON_VERSION: "3.6"
    #     SQLALCHEMY_VERSION: "1.1"
    #     SPARK_PY4J: "python/lib/py4j-0.10.7-src.zip"
    #     AIRFLOW_SUBPACKAGES: ""
    network_mode: "host"
    volumes_from:
      - scheduler
    ports:
      - 8080:8080
    environment:
      AIRFLOW__CORE__FERNET_KEY: 8NE6O6RcTJpxcCkuKxOHOExzIJkXkeJKbRie03a69dI=
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://fixme:fixme@localhost:5999/airflow
      AIRFLOW_USER: fixme
      AIRFLOW_EMAIL: fixme@fix.me
      AIRFLOW_PASSWORD: fixme
      TZ: "Europe/Amsterdam"  # Doesn't affect DAG trigger / cron (webserver doesn't do timezone in the first place)
    restart: always
volumes:
  postgres: {}
  airflow_logs: {}
