#!/usr/bin/env bash
set -euo pipefail

IMAGE_NAME=${IMAGE_NAME:-airflow-pipeline}

if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
    TEST_IMAGE_NAME="test-${IMAGE_NAME}"

    for SELECTED_PYTHON_MAJOR_VERSION in "2" "3"; do
        ORIGINAL_IMAGE="${DOCKER_USERNAME}/${IMAGE_NAME}:${AIRFLOW_VERSION}_spark-${SPARK_VERSION}_hadoop-${HADOOP_VERSION}_sqlalchemy-${SQLALCHEMY_VERSION}_py-${SELECTED_PYTHON_MAJOR_VERSION}"
        TEST_IMAGE="${DOCKER_USERNAME}/${TEST_IMAGE_NAME}:${AIRFLOW_VERSION}_spark-${SPARK_VERSION}_hadoop-${HADOOP_VERSION}_sqlalchemy-${SQLALCHEMY_VERSION}_py-${SELECTED_PYTHON_MAJOR_VERSION}"
        docker tag "${ORIGINAL_IMAGE}" "${TEST_IMAGE}"
    done

    IMAGE_NAME="${TEST_IMAGE_NAME}"
fi

docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"

for SELECTED_PYTHON_MAJOR_VERSION in "2" "3"; do
    docker push "${DOCKER_USERNAME}/${IMAGE_NAME}:${AIRFLOW_VERSION}_spark-${SPARK_VERSION}_hadoop-${HADOOP_VERSION}_sqlalchemy-${SQLALCHEMY_VERSION}_py-${SELECTED_PYTHON_MAJOR_VERSION}"
done
